// Safe Caddy configuration generation.
//
// OS1 NEVER accepts a raw Caddyfile or arbitrary directives from the UI/API.
// A Caddyfile is generated ONLY from validated structured values (a list of
// hostnames + the fixed internal upstream). The output is deterministic and
// contains no user-controlled directives — each hostname is re-validated here as
// a last line of defense before it is written into config.
import { validateHostname } from './hostname';

// The app is only ever reachable to Caddy over the internal Docker network on
// this fixed upstream. This is a constant, never operator-supplied.
export const APP_UPSTREAM = 'app:3000';

export type CaddySite = { hostname: string };

export type CaddyGenResult =
  | { ok: true; caddyfile: string; hostnames: string[] }
  | { ok: false; reason: string };

/**
 * Generate a Caddyfile from a structured list of sites. Rejects the whole
 * request if ANY hostname fails strict validation — we never emit a partial or
 * best-effort config. Caddy handles ACME, Let's Encrypt issuance, storage,
 * automatic renewal, HTTP→HTTPS redirect, SNI and reloads automatically; the
 * generated config is intentionally minimal.
 */
export function generateCaddyfile(sites: CaddySite[]): CaddyGenResult {
  if (!Array.isArray(sites) || sites.length === 0) {
    return { ok: false, reason: 'no sites to configure' };
  }
  const hostnames: string[] = [];
  for (const s of sites) {
    const v = validateHostname(s?.hostname);
    if (!v.ok) return { ok: false, reason: `invalid hostname: ${v.reason}` };
    if (hostnames.includes(v.hostname)) continue; // de-dupe
    hostnames.push(v.hostname);
  }

  const header =
    '# Generated by OS1 Fiber Track Pro — DO NOT EDIT BY HAND.\n' +
    '# Regenerated from validated structured values whenever a domain changes.\n' +
    '# Caddy manages ACME/Let\u2019s Encrypt issuance, storage, renewal and\n' +
    '# HTTP→HTTPS redirect automatically. Certificate keys live only in the\n' +
    '# caddy_data volume and are never exposed here.\n';

  const blocks = hostnames
    .map(
      (h) =>
        `${h} {\n` +
        `\treverse_proxy ${APP_UPSTREAM}\n` +
        `\tencode zstd gzip\n` +
        `}\n`
    )
    .join('\n');

  return { ok: true, caddyfile: `${header}\n${blocks}`, hostnames };
}

/**
 * Validate a generated Caddyfile before it is written/reloaded. This guards
 * against a config that somehow contains anything other than the fixed, safe
 * directives we generate (defense in depth against injection).
 */
export function validateGeneratedConfig(caddyfile: string): { ok: boolean; reason?: string } {
  if (typeof caddyfile !== 'string' || !caddyfile.trim()) {
    return { ok: false, reason: 'empty config' };
  }
  // Only these directives are ever emitted by generateCaddyfile.
  const ALLOWED_DIRECTIVES = new Set(['reverse_proxy', 'encode']);
  const lines = caddyfile.split('\n');
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line === '}') continue;
    // Site opener:  "<hostname> {"
    if (line.endsWith('{')) {
      const host = line.slice(0, -1).trim();
      if (!validateHostname(host).ok) {
        return { ok: false, reason: 'config contains an invalid site address' };
      }
      continue;
    }
    // Otherwise it must be an allowed directive line.
    const directive = line.split(/\s+/)[0];
    if (!ALLOWED_DIRECTIVES.has(directive)) {
      return { ok: false, reason: `disallowed directive: ${directive}` };
    }
    // The reverse_proxy target must be the fixed internal upstream.
    if (directive === 'reverse_proxy' && !line.includes(APP_UPSTREAM)) {
      return { ok: false, reason: 'reverse_proxy target is not the internal app upstream' };
    }
  }
  return { ok: true };
}

// Where the generated Caddyfile is written on the shared persistent volume that
// both the app (writer) and the proxy (reader) mount. Overridable for tests.
export const GENERATED_CADDYFILE_PATH =
  process.env.CADDY_GENERATED_PATH || '/caddy-generated/sites.caddy';

/**
 * Produce a REDACTED, read-only view of the generated config for the advanced
 * diagnostics panel. There are no secrets in a generated Caddyfile, but this
 * keeps the contract explicit and future-proof.
 */
export function redactConfigForDisplay(caddyfile: string): string {
  return caddyfile.replace(/(password|token|secret|key)\s+\S+/gi, '$1 [REDACTED]');
}
