// Domain & SSL control-plane service layer.
//
// This is the single orchestration point for all Domain & SSL operations. API
// routes call into these functions; they never touch DNS/network/cert/proxy
// primitives directly. Every mutating operation:
//   * re-validates the hostname,
//   * updates the HostedDomain record,
//   * writes an audit entry (via the caller, which has the actor/request meta),
//   * maps low-level failures to operator-safe DOMAIN_ERROR strings.
//
// SECURITY: no arbitrary shell is ever executed here. Proxy configuration is
// generated ONLY from validated structured values and written to a fixed path on
// a shared persistent volume; Caddy (run with --watch) picks it up and performs
// ACME/issuance/renewal itself. Certificate PRIVATE KEYS are never read here.
import { prisma } from '@/lib/prisma';
import { validateHostname } from './hostname';
import { resolveDomain } from './dns';
import { detectPublicIp, checkPort } from './network';
import { inspectCertificate, statusFromValidity } from './cert';
import {
  generateCaddyfile,
  validateGeneratedConfig,
  GENERATED_CADDYFILE_PATH,
} from './caddy';
import {
  DOMAIN_STATUS,
  DNS_STATUS,
  SSL_STATUS,
  DOMAIN_ERROR,
  RATE_LIMITS,
} from './index';
import { promises as fs } from 'fs';
import path from 'path';

export type ServiceResult<T = unknown> = {
  ok: boolean;
  error?: string; // always an operator-safe DOMAIN_ERROR string when ok=false
  data?: T;
};

// ---- In-memory best-effort rate limiter (see §17) ---------------------------
// Coarse guard against accidental hammering / Let's Encrypt rate-limit burn.
// Keyed by "operation:identifier" (identifier is typically the domain id).
type RateKind = keyof typeof RATE_LIMITS;
const rateState = new Map<string, number[]>();

export function checkRateLimit(op: RateKind, key: string): boolean {
  const cfg = RATE_LIMITS[op];
  const now = Date.now();
  const bucketKey = `${op}:${key}`;
  const hits = (rateState.get(bucketKey) || []).filter((t) => now - t < cfg.windowMs);
  if (hits.length >= cfg.max) {
    rateState.set(bucketKey, hits);
    return false;
  }
  hits.push(now);
  rateState.set(bucketKey, hits);
  return true;
}

// ---- Helpers ----------------------------------------------------------------
async function getDomainOrNull(id: string) {
  return prisma.hostedDomain.findUnique({ where: { id } });
}

function joinIps(ips: string[]): string | null {
  return ips.length ? ips.join(',') : null;
}

/**
 * Regenerate the proxy configuration from the CURRENT set of SSL-enabled
 * domains and write it to the shared persistent volume. Caddy (run with --watch)
 * auto-reloads. Returns an operator-safe error on any failure.
 *
 * LIVE-VM: the actual Caddy reload + ACME issuance require the running proxy
 * container and public reachability. Here we generate + validate + persist the
 * config deterministically; that part is fully testable.
 */
export async function regenerateProxyConfig(): Promise<ServiceResult<{ hostnames: string[] }>> {
  const domains = await prisma.hostedDomain.findMany({
    where: { sslEnabled: true, status: { not: DOMAIN_STATUS.DISABLED } },
    orderBy: { createdAt: 'asc' },
  });
  const sites = domains.map((d) => ({ hostname: d.hostname }));

  // With no SSL-enabled domains we still write a valid (empty-of-sites) config
  // so the proxy has a deterministic file to import.
  if (sites.length === 0) {
    try {
      await writeProxyConfig('# Generated by OS1 — no SSL-enabled domains configured.\n');
      return { ok: true, data: { hostnames: [] } };
    } catch {
      return { ok: false, error: DOMAIN_ERROR.PROXY_RELOAD_FAILED };
    }
  }

  const gen = generateCaddyfile(sites);
  if (!gen.ok) return { ok: false, error: DOMAIN_ERROR.PROXY_CONFIG_INVALID };
  const valid = validateGeneratedConfig(gen.caddyfile);
  if (!valid.ok) return { ok: false, error: DOMAIN_ERROR.PROXY_CONFIG_INVALID };

  try {
    await writeProxyConfig(gen.caddyfile);
  } catch {
    return { ok: false, error: DOMAIN_ERROR.PROXY_RELOAD_FAILED };
  }
  return { ok: true, data: { hostnames: gen.hostnames } };
}

async function writeProxyConfig(contents: string): Promise<void> {
  const target = GENERATED_CADDYFILE_PATH;
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, contents, { encoding: 'utf8', mode: 0o644 });
}

// ---- Verify -----------------------------------------------------------------
/**
 * Verify a domain: resolve DNS, compare against the appliance public IP, and
 * probe ports 80/443. Updates the record with explicit statuses. Does NOT
 * request a certificate — that is a separate, gated step (§3).
 */
export async function verifyDomain(id: string): Promise<ServiceResult> {
  const domain = await getDomainOrNull(id);
  if (!domain) return { ok: false, error: DOMAIN_ERROR.INVALID_HOSTNAME };

  const v = validateHostname(domain.hostname);
  if (!v.ok) {
    await prisma.hostedDomain.update({
      where: { id },
      data: { status: DOMAIN_STATUS.DNS_ERROR, lastError: DOMAIN_ERROR.INVALID_HOSTNAME, lastVerifiedAt: new Date() },
    });
    return { ok: false, error: DOMAIN_ERROR.INVALID_HOSTNAME };
  }

  await prisma.hostedDomain.update({ where: { id }, data: { status: DOMAIN_STATUS.VERIFYING } });

  // Public IP: configured override wins; else auto-detect (LIVE-VM).
  const publicIp = await detectPublicIp({ ipv4: domain.expectedIpv4, ipv6: domain.expectedIpv6 });
  const expectedIpv4 = domain.expectedIpv4 || publicIp.ipv4;
  const expectedIpv6 = domain.expectedIpv6 || publicIp.ipv6;

  const dnsRes = await resolveDomain(v.hostname, { ipv4: expectedIpv4, ipv6: expectedIpv6 });

  // Port reachability (LIVE-VM meaningful only where 80/443 route here).
  const [http, https] = await Promise.all([
    checkPort(v.hostname, 80),
    checkPort(v.hostname, 443),
  ]);

  let status: string = DOMAIN_STATUS.READY;
  let lastError: string | null = null;

  if (dnsRes.status === DNS_STATUS.NXDOMAIN || dnsRes.status === DNS_STATUS.MISMATCH || dnsRes.status === DNS_STATUS.ERROR) {
    status = DOMAIN_STATUS.DNS_ERROR;
    lastError = DOMAIN_ERROR.DNS_NOT_POINTING;
  } else if (!http) {
    status = DOMAIN_STATUS.PORT_ERROR;
    lastError = DOMAIN_ERROR.PORT_80_UNREACHABLE;
  } else if (!https) {
    // Port 443 may be closed before SSL is enabled; surface as informational but
    // still allow proceeding to enable SSL (Caddy opens 443 once configured).
    status = DOMAIN_STATUS.READY;
    lastError = null;
  }

  const updated = await prisma.hostedDomain.update({
    where: { id },
    data: {
      status,
      dnsStatus: dnsRes.status,
      resolvedIpv4: joinIps(dnsRes.ipv4),
      resolvedIpv6: joinIps(dnsRes.ipv6),
      expectedIpv4,
      expectedIpv6,
      httpReachable: http,
      httpsReachable: https,
      lastVerifiedAt: new Date(),
      lastError,
    },
  });

  const ok = status === DOMAIN_STATUS.READY;
  return { ok, error: ok ? undefined : (lastError ?? DOMAIN_ERROR.DNS_NOT_POINTING), data: updated };
}

// ---- Enable SSL -------------------------------------------------------------
/**
 * Enable SSL for a verified domain. Marks the domain ISSUING, regenerates the
 * proxy config (which triggers Caddy ACME issuance), and lets Caddy obtain the
 * certificate. Actual issuance is LIVE-VM; here we flip state + persist config.
 */
export async function enableSsl(id: string): Promise<ServiceResult> {
  const domain = await getDomainOrNull(id);
  if (!domain) return { ok: false, error: DOMAIN_ERROR.INVALID_HOSTNAME };

  // Must be verified first (§3): don't request a cert until verify passes.
  if (domain.status !== DOMAIN_STATUS.READY && domain.status !== DOMAIN_STATUS.ACTIVE && domain.status !== DOMAIN_STATUS.RENEWAL_DUE && domain.status !== DOMAIN_STATUS.CERT_ERROR) {
    return { ok: false, error: DOMAIN_ERROR.NOT_VERIFIED };
  }

  await prisma.hostedDomain.update({
    where: { id },
    data: { sslEnabled: true, status: DOMAIN_STATUS.ISSUING, sslStatus: SSL_STATUS.ISSUING, lastError: null },
  });

  const proxy = await regenerateProxyConfig();
  if (!proxy.ok) {
    await prisma.hostedDomain.update({
      where: { id },
      data: { status: DOMAIN_STATUS.CERT_ERROR, sslStatus: SSL_STATUS.ERROR, lastError: proxy.error },
    });
    return { ok: false, error: proxy.error };
  }

  const updated = await prisma.hostedDomain.update({
    where: { id },
    data: { lastIssuedAt: new Date() },
  });
  return { ok: true, data: updated };
}

// ---- Reissue ----------------------------------------------------------------
/**
 * Force a certificate reissue: regenerate the proxy config so Caddy re-runs
 * ACME. LIVE-VM for the actual issuance.
 */
export async function reissue(id: string): Promise<ServiceResult> {
  const domain = await getDomainOrNull(id);
  if (!domain) return { ok: false, error: DOMAIN_ERROR.INVALID_HOSTNAME };
  if (!domain.sslEnabled) return { ok: false, error: DOMAIN_ERROR.NOT_VERIFIED };

  await prisma.hostedDomain.update({
    where: { id },
    data: { status: DOMAIN_STATUS.ISSUING, sslStatus: SSL_STATUS.ISSUING, lastError: null },
  });

  const proxy = await regenerateProxyConfig();
  if (!proxy.ok) {
    await prisma.hostedDomain.update({
      where: { id },
      data: { status: DOMAIN_STATUS.CERT_ERROR, sslStatus: SSL_STATUS.ERROR, lastError: proxy.error },
    });
    return { ok: false, error: proxy.error };
  }

  const updated = await prisma.hostedDomain.update({
    where: { id },
    data: { lastIssuedAt: new Date() },
  });
  return { ok: true, data: updated };
}

// ---- Refresh certificate status ---------------------------------------------
/**
 * Inspect the live certificate (public metadata only) and update the record.
 * LIVE-VM: needs a reachable, certificate-serving endpoint.
 */
export async function refreshCertificate(id: string): Promise<ServiceResult> {
  const domain = await getDomainOrNull(id);
  if (!domain) return { ok: false, error: DOMAIN_ERROR.INVALID_HOSTNAME };

  const info = await inspectCertificate(domain.hostname);
  if (info.error) {
    // Don't clobber a known-good state on a transient probe failure; just record.
    return { ok: false, error: DOMAIN_ERROR.ISSUANCE_FAILED };
  }

  const sslStatus = statusFromValidity(info.notAfter);
  const status =
    sslStatus === SSL_STATUS.ACTIVE
      ? DOMAIN_STATUS.ACTIVE
      : sslStatus === SSL_STATUS.RENEWAL_DUE
        ? DOMAIN_STATUS.RENEWAL_DUE
        : sslStatus === SSL_STATUS.EXPIRED
          ? DOMAIN_STATUS.CERT_ERROR
          : domain.status;

  const updated = await prisma.hostedDomain.update({
    where: { id },
    data: {
      certificateIssuer: info.issuer,
      certificateSerial: info.serial,
      certificateNotBefore: info.notBefore,
      certificateNotAfter: info.notAfter,
      sslStatus,
      status,
      httpsReachable: true,
      lastError: sslStatus === SSL_STATUS.EXPIRED ? DOMAIN_ERROR.CERT_EXPIRED : null,
    },
  });
  return { ok: true, data: updated };
}

// ---- Disable ----------------------------------------------------------------
/**
 * Disable SSL / the domain. Regenerates the proxy config so the domain is no
 * longer served. Certificate material remains in the caddy_data volume (Caddy
 * manages it); OS1 never deletes keys.
 */
export async function disableDomain(id: string): Promise<ServiceResult> {
  const domain = await getDomainOrNull(id);
  if (!domain) return { ok: false, error: DOMAIN_ERROR.INVALID_HOSTNAME };

  await prisma.hostedDomain.update({
    where: { id },
    data: { sslEnabled: false, status: DOMAIN_STATUS.DISABLED, sslStatus: SSL_STATUS.NONE, isPrimary: false },
  });

  const proxy = await regenerateProxyConfig();
  if (!proxy.ok) {
    return { ok: false, error: proxy.error };
  }
  const updated = await getDomainOrNull(id);
  return { ok: true, data: updated };
}
